version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    branches:
      only:
        - master
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: ~/gcloud-service-key.json
      - PROJECT_ID: okapi-173322
      - CLUSTER_NAME: okapi
      - CLOUDSDK_COMPUTE_ZONE: us-central1-a
      - DOCKER_IMAGE_NAME: folioci/mod-kb-ebsco
      - KUBE_DEPLOYMENT_NAME: mod-kb-ebsco
      - KUBE_DEPLOYMENT_CONTAINER_NAME: mod-kb-ebsco
      - OKAPI_EXTERNAL_ADDRESS: https://okapi.frontside.io
      - FOLIO_MODULE_NAME: mod-kb-ebsco
      - FOLIO_TENANT_ID: fs
      - MODULE_VERSION: 0.1.1
    steps:
      - checkout
      - run:
          name: Checkout mod-kb-ebsco
          command: |
            cd ~/
            git clone --branch=master https://github.com/folio-org/mod-kb-ebsco.git
      - run:
          name: Install jq >=1.5
          command: |
            echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/sources.list
            apt-get update
            apt-get -y -t jessie-backports install "jq"
      - run:
          name: Connect to Frontside Okapi Cluster
          command: |
            gcloud --quiet version
            echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $PROJECT_ID
            gcloud --quiet config set container/cluster $CLUSTER_NAME
            gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials $CLUSTER_NAME
      - run:
          name: Deploy to Frontside Okapi Cluster
          command: ./deploy.sh
